final standards = [
  [0, 1],
  [1, 2],
  [2, 3],
  [3, 4],
];

final subjects = [
  [0, "English"],
  [1, "Hindi"],
  [2, "Maths"],
  [3, "Science"],
  [4, "Social Science"],
  [5, "Computer Science"],
  [6, "Sanskrit"],
  [7, "French"],
  [8, "German"],
  [9, "Spanish"],
  [10, "Urdu"],
  [11, "Tamil"],
  [12, "Telugu"],
  [13, "Malayalam"],
  [14, "Kannada"],
  [15, "Gujarati"],
  [16, "Marathi"],
  [17, "Bengali"],
  [18, "Odia"],
  [19, "Punjabi"],
  [20, "Arabic"],
  [21, "Persian"],
  [22, "Russian"],
  [23, "Chinese"],
  [24, "Japanese"],
  [25, "Other"]
];
